### ISSUE TITLE
Enable retries for GFE client throttling

### ISSUE THREAD

**Issue by igorbernstein2** [googleapis/java-bigtable#1543] opened 2022-12-09 20:27 UTC
Under some circumstances GFE can kill a stream due to overload. It would make sense to make this a retriable error and invoke exponential retry to push back on the load.

The error comes down as
`INTERNAL: Abrupt GOAWAY closed sent stream. HTTP/2 error code: PROTOCOL_ERROR, debug data: client_throttled`

**Comment by ejona86** [comment] 2022-12-13 00:41
Retrying internal is dangerous and can lead to things like replayed queries of death. PROTOCOL_ERROR seems the wrong error code here; it sounds like there was no HTTP/2 protocol violation. It is unclear to me why ENHANCE_YOUR_CALM wasn't used instead. ENHANCE_YOUR_CALM [is mapped](https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-HTTP2.md) to gRPC status RESOURCE_EXHAUSTED.

**Comment by igorbernstein2** [comment] 2022-12-13 15:44
@ejona86 take a look at b/261946753#comment6 and b/262072291. Let me know if you still think mitigating it on the clientside by retrying `client_throttled` errors is still wrong. My understanding is that this is similar to go/rst_stream

**Comment by ejona86** [comment] 2022-12-19 20:34
go/rst_stream didn't know the cause. It was quite troublesome, and might have been caused by the client, a proxy, or the backend. Although I also didn't notice anybody from gRPC team (nor GFE?) on that doc.

In this case, we have the clear error reason `client_throttled` and the server is obviously using the wrong HTTP/2 error code. This seems like a one-line change to fix the proxy. Looking at b/262072291, this has already been fixed in cl/496413349 by changing the error code to NO_ERROR. That will map to UNAVAILABLE in gRPC.

**Closed** 2023-10-27 16:24 UTC
Labels: api: bigtable
