### ISSUE TITLE
Bigtable emulator rejects fuzzy key filters using integer values over 127

### ISSUE THREAD

**Issue by naveg** [googleapis/java-bigtable#378] opened 2020-08-05 22:08 UTC
#### Environment details

OS type and version: Arch Linux (kernal 5.7.12)
Java version: AdoptOpenJDK 14.0.1+7
bigtable version(s): google-cloud-bigtable-emulator 0.123.0

#### Steps to reproduce

  1. Create a table that uses integer keys. In our case, each row key is 5 integers or 20 bytes. Byte keys are created by calling Bytes.toBytes(x) on each integer and concatenating the results, so the first 4 bytes are the first integer, etc.
  2. Insert some data
  3. Build a scan with a fuzzy filter.
  4. When all the integers in the fuzzy filter keys are below 128, everything works. If any are 128 or higher, it fails. I tested our code with [127,0,0,0,0] (works) and [128,0,0,0,0] (fails).

#### Code example

See tickets and PRs linked below, which have some potentially relevant sample code.

#### Stack trace

```
Aug. 05, 2020 3:02:34 P.M. com.google.cloud.bigtable.emulator.v2.Emulator$2 run
WARNING: 2020/08/05 15:02:34 Bad pattern "\\x00\\x00\\x00\x80\\C\\C\\C\\C\\C\\C\\C\\C\\C\\C\\C\\C\\C\\C\\C\\C\\C*": error parsing regexp: invalid UTF-8: `�\C\C\C\C\C\C\C\C\C\C\C\C\C\C\C\C\C*)$`
2020-08-05 15:02:34,055 3744 [grpc-default-executor-0] ERROR c.g.c.b.g.a.AbstractRetryingOperation - Could not complete RPC. Failure #0, got: Status{code=INVALID_ARGUMENT, description=Error in field 'rowkey_regex_filter' : error parsing regexp: invalid UTF-8: `�\C\C\C\C\C\C\C\C\C\C\C\C\C\C\C\C\C*)$`, cause=null} on channel 3.

... snip ...

Caused by: com.google.cloud.bigtable.grpc.io.IOExceptionWithStatus: Error in response stream
	at com.google.cloud.bigtable.grpc.scanner.ResultQueueEntry$ExceptionResultQueueEntry.getResponseOrThrow(ResultQueueEntry.java:100)
	at com.google.cloud.bigtable.grpc.scanner.ResponseQueueReader.getNextMergedRow(ResponseQueueReader.java:100)
	at com.google.cloud.bigtable.grpc.scanner.ResumingStreamingResultScanner.next(ResumingStreamingResultScanner.java:78)
	at com.google.cloud.bigtable.grpc.scanner.ResumingStreamingResultScanner.next(ResumingStreamingResultScanner.java:33)
	at com.google.cloud.bigtable.hbase.adapters.read.BigtableResultScannerAdapter$1.next(BigtableResultScannerAdapter.java:63)
	at org.apache.hadoop.hbase.client.AbstractClientScanner$1.hasNext(AbstractClientScanner.java:92)
	... 71 more
Caused by: io.grpc.StatusRuntimeException: INVALID_ARGUMENT: Error in field 'rowkey_regex_filter' : error parsing regexp: invalid UTF-8: `�\C\C\C\C\C\C\C\C\C\C\C\C\C\C\C\C\C*)$`
	at io.grpc.Status.asRuntimeException(Status.java:524)
	at com.google.cloud.bigtable.grpc.async.AbstractRetryingOperation.onError(AbstractRetryingOperation.java:214)
	at com.google.cloud.bigtable.grpc.async.AbstractRetryingOperation.onClose(AbstractRetryingOperation.java:177)
	at com.google.cloud.bigtable.grpc.scanner.RetryingReadRowsOperation.onClose(RetryingReadRowsOperation.java:217)
	at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at com.google.cloud.bigtable.grpc.io.Watchdog$WatchedCall$1.onClose(Watchdog.java:180)
	at com.google.cloud.bigtable.grpc.io.ChannelPool$InstrumentedChannel$2.onClose(ChannelPool.java:212)
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:426)
	at io.grpc.internal.ClientCallImpl.access$500(ClientCallImpl.java:66)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:689)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$900(ClientCallImpl.java:577)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:751)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:740)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
```

#### Any additional information below

Similar issues that seems relevant:

https://github.com/googleapis/java-bigtable-hbase/issues/1770
https://github.com/googleapis/java-bigtable-hbase/issues/1703

I suspect that this test case may fail when run against the bigtable emulator, but I have not tried: https://github.com/googleapis/java-bigtable-hbase/pull/1782

**Comment by Naveg** [comment] 2020-08-18 21:44
@kolea2 any sense of when this might be fixed? It's preventing us from making a substantial performance improvement in our app.

**Comment by igorbernstein2** [comment] 2020-12-17 22:10
After a bit more thought, this is definitely an emulator bug and should be fixed there instead of every client.
I think this is already a known issue: https://github.com/googleapis/google-cloud-go/issues/1373

I'm going to close this in favor of fixing the root cause

**Comment by dmitry-fa** [comment] 2020-12-18 14:32
The reported problem is caused not by the emulator but incorrect behavior of FuzzyRowFilterAdapter which doesn't escape negative bytes while converting byte[] to regex string. As a result regex string contains `\377` instead of `\\377`

The following code demonstrates the bug:
```
    FuzzyRowFilter fuzzy = new FuzzyRowFilter(ImmutableList.of(Pair.newPair(new byte[] {-1}, new byte[] {0})));
    Filters.Filter filter = FilterAdapter.buildAdapter().adaptFilter(null, fuzzy).get();
    System.out.println(filter.toProto());
    Filters.Filter filter1 = FILTERS.key().regex("\377\\C*");
    Filters.Filter filter2 = FILTERS.key().regex("\\377\\C*");
    System.out.println(filter1.toProto());
    System.out.println(filter2.toProto());
```

row_key_regex_filter: "\377\\C*"

row_key_regex_filter: "\303\277\\C*"

row_key_regex_filter: "\\377\\C*"

So, I reopen the issue.

**Comment by crwilcox** [comment] 2021-06-17 16:33
Is this issue misnamed? It seems it was originally thought to be an emulator issue, but has since been reduced to being an implementation issue in the java client. Is that a correct interpretation?

**Comment by Naveg** [comment] 2021-06-17 17:21
I'm not familiar with the internals, but this issue does not occur in production. It only occurs with the bigtable emulator. Same client and application code

**Comment by crwilcox** [comment] 2021-06-21 20:45
Thanks @Naveg . I think the comment https://github.com/googleapis/java-bigtable/issues/378#issuecomment-748115107 led me astray from your repro.

**Comment by crwilcox** [comment] 2021-07-27 01:00
If this issue only occurs against the emulator, it doesn't seem likely there is an issue in the client. it seems more likely the behavior of the emulator given the same request doesn't match production. 

I assume googleapis/google-cloud-go#1373 fully captures the underlying gap in the emulator.

**Closed** 2023-06-22 01:35 UTC
Labels: priority: p2, external, type: bug, api: bigtable
